#!/bin/bash
# ROServices Installer - created and maintained by ROServices
# General
INSTALLER_VERSION="v1.2.10"
STEPS=17
# Colors
BLUE='\033[0;36m'
GREEN='\033[0;92m'
YELLOW='\033[0;93m'
NC='\033[0m'

# Credentials
USERID=$(date +%s | sha256sum | base64 | head -c 3 ; echo)
USERPASS=$(date +%s | sha256sum | base64 | head -c 6 ; echo)
RATHENAPASS="#R0$3rv1c3$#"
RAGSQLPASS=$(date +%s | sha256sum | base64 | head -c 10 ; echo)

# URLs
URL_RA="https://rathena.org/board"
URL_RAGIT="https://github.com/rathena/rathena"
URL_FLUXGIT="https://github.com/rathena/FluxCP"
SERVER_IPLIST=$(ip addr|awk '/eth0/ && /inet/ {gsub(/\/[0-9][0-9]/,""); print $2}')
SERVER_IP=$(echo $SERVER_IPLIST | cut -d ' ' -f 1 )

VERSION="${INSTALLER_VERSION}"

echo "\033c"
echo "Welcome to ${BLUE}ROServices${NC}, an unattended installer made for you."
echo "Version: ${VERSION}\n"
echo "This script will now begin to install stuff on your system. Please be patient as this could take a while!\n"



echo "${BLUE}Step 1/${STEPS}:${NC} Updating your OS"
apt-get -qy update > /dev/null
apt-get -qy upgrade > /dev/null
echo ""



echo "${BLUE}Step 2/${STEPS}:${NC} Installing Prerequisites"
apt-get -qy install expect wget sudo > /dev/null
echo ""



echo "${BLUE}Step 3/${STEPS}:${NC} Installing MySQL Stuff"
apt-get -qy install libaio1 libdbd-mariadb-perl libdbi-perl libterm-readkey-perl libhtml-template-perl > /dev/null
export DEBIAN_FRONTEND=noninteractive 
bash -c 'debconf-set-selections <<< "mariadb-server mariadb-server/root_password password ragnarok"'
bash -c 'debconf-set-selections <<< "mariadb-server mariadb-server/root_password_again password ragnarok"'

apt-get -qy install mariadb-server
wget -q https://raw.githubusercontent.com/roservices/RO_Installer/roservices_scripts/msi.sh
chmod +x msi.sh
./msi.sh
rm msi.sh



echo "${BLUE}Step 4/${STEPS}:${NC} Installing Apache2 & PHP"
echo " * Installing Apache2"
apt-get -qy install apache2 > /dev/null
echo " * Installing PHP"
apt-get -qy install libapache2-mod-php php-mysql php-gd php-mbstring php-xml > /dev/null
systemctl restart apache2
echo ""



echo "${BLUE}Step 5/${STEPS}:${NC} Installing Desktop VNC packages"
echo "This step can take a while...."
echo " * Installing xfce"
apt-get -qy install xfce4 xfce4-goodies > /dev/null
echo " * Installing VNCServer"
apt-get -qy install gnome-icon-theme tightvncserver > /dev/null
wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
apt-get -qy install ./google-chrome-stable_current_amd64.deb
echo ""




echo "${BLUE}Step 6/${STEPS}:${NC} Installing rA specific packages"
echo " * Installing git, make, g++"
apt-get -qy install git make libmariadb-dev libmariadbclient-dev libmariadbclient-dev-compat > /dev/null
echo " * Installing Utilities"
apt-get -qy install zlib1g-dev libpcre3-dev nano zip unzip zenity gcc g++ > /dev/null
echo ""



echo "${BLUE}Step 7/${STEPS}:${NC} Creating User: roservices"
echo "${YELLOW}This process is automatic and doesn't require user input.${NC}"
echo "${YELLOW}Please do not type at the password prompt.${NC}"
sudo useradd roservices
wget -q https://raw.githubusercontent.com/roservices/RO_Installer/roservices_scripts/useraddpasswd.sh
chmod +x useraddpasswd.sh
./useraddpasswd.sh $RATHENAPASS
rm useraddpasswd.sh
gpasswd -a roservices sudo
echo ""



echo "${BLUE}Step 8/${STEPS}:${NC} Setting Up Desktop Stuff"
mkdir -p /usr/share/roservices/
cd /usr/share/roservices/
wget -q https://raw.githubusercontent.com/roservices/RO_Installer/roservices_scripts/files.zip
unzip -qq files.zip
cd links
mkdir -p /home/roservices/Desktop
cp -R * /home/roservices/Desktop
cd /usr/share/roservices/scripts
chmod +x *
cd /home/roservices/Desktop
chmod +x *
echo ""



echo "${BLUE}Step 9/${STEPS}:${NC} Creating VNC Server Start-up Files"
cd /usr/local/bin
wget -q https://raw.githubusercontent.com/roservices/RO_Installer/roservices_scripts/myvncserver
chmod +x myvncserver
cd /lib/systemd/system/
wget -q https://raw.githubusercontent.com/roservices/RO_Installer/roservices_scripts/myvncserver.service
systemctl daemon-reload
systemctl enable myvncserver.service
echo ""



echo "${BLUE}Step 10/${STEPS}:${NC} Installing ROServices Files"
chown -R roservices:roservices /home/roservices
chown -R roservices:roservices /usr/share/roservices
cd /home/roservices
sudo -u roservices sh -c "wget -q https://raw.githubusercontent.com/roservices/RO_Installer/roservices_scripts/vnc.sh"
sudo -u roservices sh -c "chmod +x vnc.sh"
sudo -u roservices sh -c "./vnc.sh $RATHENAPASS"
rm vnc.sh
sudo -u roservices sh -c "myvncserver stop"
mkdir -p /home/roservices/.config/xfce4/xfconf/xfce-perchannel-xml/
touch /home/roservices/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" >> /home/roservices/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "<channel name=\"xfce4-desktop\" version=\"1.0\">" >> /home/roservices/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "  <property name=\"backdrop\" type=\"empty\">" >> /home/roservices/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "    <property name=\"screen0\" type=\"empty\">" >> /home/roservices/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "      <property name=\"monitor0\" type=\"empty\">" >> /home/roservices/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "        <property name=\"brightness\" type=\"empty\"/>" >> /home/roservices/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "        <property name=\"color1\" type=\"empty\"/>" >> /home/roservices/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "        <property name=\"color2\" type=\"empty\"/>" >> /home/roservices/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "        <property name=\"color-style\" type=\"empty\"/>" >> /home/roservices/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "        <property name=\"image-path\" type=\"string\" value=\"/usr/share/roservices/img/bg.png\"/>" >> /home/roservices/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "        <property name=\"image-show\" type=\"empty\"/>" >> /home/roservices/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "        <property name=\"last-image\" type=\"empty\"/>" >> /home/roservices/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "        <property name=\"last-single-image\" type=\"string\" value=\"/usr/share/roservices/img/bg.png\"/>" >> /home/roservices/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "      </property>" >> /home/roservices/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "    </property>" >> /home/roservices/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "  </property>" >> /home/roservices/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "  <property name=\"desktop-icons\" type=\"empty\">" >> /home/roservices/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "    <property name=\"icon-size\" type=\"uint\" value=\"32\"/>" >> /home/roservices/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "  </property>" >> /home/roservices/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml
echo "</channel>" >> /home/roservices/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml

touch /home/roservices/.config/mimeapps.list
echo "[Default Applications]" >> /home/roservices/.config/mimeapps.list
echo "text/plain=mousepad.desktop" >> /home/roservices/.config/mimeapps.list
echo "" >> /home/roservices/.config/mimeapps.list
echo "[Added Associations]" >> /home/roservices/.config/mimeapps.list
echo "text/plain=mousepad.desktop;" >> /home/roservices/.config/mimeapps.list
echo ""
chown -R roservices:roservices /home/roservices/



echo "${BLUE}Step 11/${STEPS}:${NC} Grabbing rA Source Files"
sudo -u roservices sh -c "git clone -q ${URL_RAGIT} /home/roservices/Desktop/rAthena/"
echo ""



echo "${BLUE}Step 12/${STEPS}:${NC} Performing Initial rA Compile"
echo "This step will take time.. please be patient"
echo "You may see warnings here - this is normal"
cd /home/roservices/Desktop/rAthena
sudo -u roservices sh -c "./configure > /dev/null"
sudo -u roservices sh -c "make server > /dev/null"
sudo -u roservices sh -c "chmod a+x login-server && chmod a+x char-server && chmod a+x map-server"
echo ""



echo "${BLUE}Step 13/${STEPS}:${NC} Creating MySQL Database"
mysqladmin -u root -pragnarok create ragnarok
mysql -u root -pragnarok -e "CREATE USER ragnarok@localhost IDENTIFIED BY '${USERPASS}';"
mysql -u root -pragnarok -e "GRANT ALL PRIVILEGES ON ragnarok.* TO 'ragnarok'@'localhost';"
mysql -u root -pragnarok -e "FLUSH PRIVILEGES;"
mysql -u root -pragnarok ragnarok  < /home/roservices/Desktop/rAthena/sql-files/main.sql
mysql -u root -pragnarok ragnarok  < /home/roservices/Desktop/rAthena/sql-files/logs.sql
mysql -u root -pragnarok ragnarok  < /home/roservices/Desktop/rAthena/sql-files/item_cash_db.sql
mysql -u root -pragnarok ragnarok  < /home/roservices/Desktop/rAthena/sql-files/item_cash_db2.sql
mysql -u root -pragnarok ragnarok  < /home/roservices/Desktop/rAthena/sql-files/item_db.sql
mysql -u root -pragnarok ragnarok  < /home/roservices/Desktop/rAthena/sql-files/item_db2.sql
mysql -u root -pragnarok ragnarok  < /home/roservices/Desktop/rAthena/sql-files/item_db2_re.sql
mysql -u root -pragnarok ragnarok  < /home/roservices/Desktop/rAthena/sql-files/item_db_re.sql
mysql -u root -pragnarok ragnarok  < /home/roservices/Desktop/rAthena/sql-files/mob_db.sql
mysql -u root -pragnarok ragnarok  < /home/roservices/Desktop/rAthena/sql-files/mob_db2.sql
mysql -u root -pragnarok ragnarok  < /home/roservices/Desktop/rAthena/sql-files/mob_db2_re.sql
mysql -u root -pragnarok ragnarok  < /home/roservices/Desktop/rAthena/sql-files/mob_db_re.sql
mysql -u root -pragnarok ragnarok  < /home/roservices/Desktop/rAthena/sql-files/mob_skill_db.sql
mysql -u root -pragnarok ragnarok  < /home/roservices/Desktop/rAthena/sql-files/mob_skill_db2.sql
mysql -u root -pragnarok ragnarok  < /home/roservices/Desktop/rAthena/sql-files/mob_skill_db2_re.sql
mysql -u root -pragnarok ragnarok  < /home/roservices/Desktop/rAthena/sql-files/mob_skill_db_re.sql
mysql -u root -pragnarok -e "USE ragnarok; UPDATE login SET userid = '${USERID}', user_pass = '${USERPASS}' where sex = 'S';"
echo ""



echo "${BLUE}Step 14/${STEPS}:${NC} Configuring FluxCP"
rm /var/www/html/index.html
git clone -q ${URL_FLUXGIT} /var/www/html/
cd /var/www/html/
wget -q https://raw.githubusercontent.com/roservices/RO_Installer/roservices_scripts/diff.diff
echo "diff --git a/config/application.php b/config/application.php" >> /var/www/html/diff.diff
echo "--- a/config/application.php" >> /var/www/html/diff.diff
echo "+++ b/config/application.php" >> /var/www/html/diff.diff
echo "@@ -3,7 +3,7 @@" >> /var/www/html/diff.diff
echo " // the default, and should be changed as needed." >> /var/www/html/diff.diff
echo " return array(" >> /var/www/html/diff.diff
echo " 	'ServerAddress'				=> 'localhost',				// This value is the hostname:port under which Flux runs. (e.g., example.com or example.com:80)" >> /var/www/html/diff.diff
echo "-	'BaseURI'					=> 'fluxcp',						// The base URI is the base web root on which your application lies." >> /var/www/html/diff.diff
echo "+	'BaseURI'					=> '',						// The base URI is the base web root on which your application lies." >> /var/www/html/diff.diff
echo " 	'InstallerPassword'			=> 'secretpassword',		// Installer/updater password." >> /var/www/html/diff.diff
echo " 	'RequireOwnership'			=> true,					// Require the executing user to be owner of the FLUX_ROOT/data/ directory tree? (Better for security)" >> /var/www/html/diff.diff
echo " 															// WARNING: This will be mostly IGNORED on non-POSIX-compliant OSes (e.g. Windows)." >> /var/www/html/diff.diff
echo "diff --git a/config/servers.php b/config/servers.php" >> /var/www/html/diff.diff
echo "--- a/config/servers.php" >> /var/www/html/diff.diff
echo "+++ b/config/servers.php" >> /var/www/html/diff.diff
echo "@@ -15,7 +15,7 @@ return array(" >> /var/www/html/diff.diff
echo " 				// -- It specifies the encoding to convert your MySQL data to on the website (most likely needs to be utf8)" >> /var/www/html/diff.diff
echo " 			'Hostname'   => '127.0.0.1'," >> /var/www/html/diff.diff
echo " 			'Username'   => 'ragnarok'," >> /var/www/html/diff.diff
echo "-			'Password'   => 'ragnarok'," >> /var/www/html/diff.diff
echo "+			'Password'   => '${USERPASS}'," >> /var/www/html/diff.diff
echo " 			'Database'   => 'ragnarok'," >> /var/www/html/diff.diff
echo " 			'Persistent' => true," >> /var/www/html/diff.diff
echo " 			'Timezone'   => null // Example: '+0:00' is UTC." >> /var/www/html/diff.diff
echo "@@ -36,7 +36,7 @@ return array(" >> /var/www/html/diff.diff
echo " 				// -- It specifies the encoding to convert your MySQL data to on the website (most likely needs to be utf8)" >> /var/www/html/diff.diff
echo " 			'Hostname'   => '127.0.0.1'," >> /var/www/html/diff.diff
echo " 			'Username'   => 'ragnarok'," >> /var/www/html/diff.diff
echo "-			'Password'   => 'ragnarok'," >> /var/www/html/diff.diff
echo "+			'Password'   => '${USERPASS}'," >> /var/www/html/diff.diff
echo " 			'Database'   => 'ragnarok'," >> /var/www/html/diff.diff
echo " 			'Persistent' => true," >> /var/www/html/diff.diff
echo " 			'Timezone'   => null // Possible values is as described in the comment in DbConfig." >> /var/www/html/diff.diff
git apply diff.diff
rm /var/www/html/diff.diff
/sbin/usermod -aG www-data roservices
chown -R www-data:www-data /var/www/html
chmod -R 0774 /var/www/html
ln -s /var/www/html /home/roservices/Desktop/FluxCP
echo ""



echo "${BLUE}Step 15/${STEPS}:${NC} Installing phpMyAdmin"
wget -q https://files.phpmyadmin.net/phpMyAdmin/4.7.3/phpMyAdmin-4.7.3-english.zip
unzip -qq phpMyAdmin-4.7.3-english.zip
rm phpMyAdmin-4.7.3-english.zip
mv phpMyAdmin-4.7.3-english phpmyadmin
cd phpmyadmin
mv config.sample.inc.php config.inc.php
echo "<?php" > /var/www/html/phpmyadmin/config.inc.php
BLOWFISH=$(date +%s | sha256sum | base64 | head -c 32 ; echo)
echo "\$cfg['blowfish_secret'] = '${BLOWFISH}';" >> /var/www/html/phpmyadmin/config.inc.php
echo "\$i=0;" >> /var/www/html/phpmyadmin/config.inc.php
echo "\$i++;" >> /var/www/html/phpmyadmin/config.inc.php
echo "\$cfg['Servers'][\$i]['host'] = 'localhost';" >> /var/www/html/phpmyadmin/config.inc.php
echo "\$cfg['Servers'][\$i]['AllowRoot'] = false;" >> /var/www/html/phpmyadmin/config.inc.php
echo "\$cfg['Servers'][\$i]['AllowNoPassword'] = false;" >> /var/www/html/phpmyadmin/config.inc.php
echo "\$cfg['Servers'][\$i]['auth_type']     = 'cookie';" >> /var/www/html/phpmyadmin/config.inc.php
chown -R www-data:www-data /var/www/html
chmod 0660 /var/www/html/phpmyadmin/config.inc.php
echo ""



echo "${BLUE}Step 16/${STEPS}:${NC} Preparing auto-config import files"
echo "//ROServices\n" >> /home/roservices/Desktop/rAthena/conf/import/char_conf.txt
echo "userid: ${USERID}" >> /home/roservices/Desktop/rAthena/conf/import/char_conf.txt
echo "passwd: ${USERPASS}" >> /home/roservices/Desktop/rAthena/conf/import/char_conf.txt
echo "char_ip: ${SERVER_IP}" >> /home/roservices/Desktop/rAthena/conf/import/char_conf.txt

echo "//ROServices\n" >> /home/roservices/Desktop/rAthena/conf/import/map_conf.txt
echo "userid: ${USERID}" >> /home/roservices/Desktop/rAthena/conf/import/map_conf.txt
echo "passwd: ${USERPASS}" >> /home/roservices/Desktop/rAthena/conf/import/map_conf.txt
echo "map_ip: ${SERVER_IP}" >> /home/roservices/Desktop/rAthena/conf/import/map_conf.txt

echo "//ROServices\n" >> /home/roservices/Desktop/rAthena/conf/import/inter_conf.txt
echo "//use_sql_db: yes" >> /home/roservices/Desktop/rAthena/conf/import/inter_conf.txt
echo "login_server_pw: ${USERPASS}" >> /home/roservices/Desktop/rAthena/conf/import/inter_conf.txt
echo "ipban_db_pw: ${USERPASS}" >> /home/roservices/Desktop/rAthena/conf/import/inter_conf.txt
echo "char_server_pw: ${USERPASS}" >> /home/roservices/Desktop/rAthena/conf/import/inter_conf.txt
echo "map_server_pw: ${USERPASS}" >> /home/roservices/Desktop/rAthena/conf/import/inter_conf.txt
echo "log_db_pw: ${USERPASS}" >> /home/roservices/Desktop/rAthena/conf/import/inter_conf.txt
echo ""

touch /home/roservices/Desktop/Info.txt
echo "ROServices\n" >> /home/roservices/Desktop/Info.txt
echo "Server IP: ${SERVER_IP}\n" >> /home/roservices/Desktop/Info.txt
echo "-- MySQL --" >> /home/roservices/Desktop/Info.txt
echo "root password is 'ragnarok', but can only be accessed locally from this system." >> /home/roservices/Desktop/Info.txt
echo "For all other MySQL uses, please use the following credentials:" >> /home/roservices/Desktop/Info.txt
echo "User: ragnarok" >> /home/roservices/Desktop/Info.txt
echo "Password: ${USERPASS}\n" >> /home/roservices/Desktop/Info.txt

echo "-- SSH User --" >> /home/roservices/Desktop/Info.txt
echo "User: roservices" >> /home/roservices/Desktop/Info.txt
echo "Password: $RATHENAPASS\n" >> /home/roservices/Desktop/Info.txt

echo "-- FluxCP --" >> /home/roservices/Desktop/Info.txt
echo " * Access FluxCP from this server using the browser and going to http://localhost" >> /home/roservices/Desktop/Info.txt
echo " or" >> /home/roservices/Desktop/Info.txt
echo " * Access FluxCP from anywhere by browsing to http://${SERVER_IP}/" >> /home/roservices/Desktop/Info.txt
echo "The Installer Password is the default for FluxCP, which is secretpassword\n" >> /home/roservices/Desktop/Info.txt

echo "-- phpMyAdmin --" >> /home/roservices/Desktop/Info.txt
echo " * Access phpMyAdmin from this server using the browser and going to http://localhost/phpmyadmin" >> /home/roservices/Desktop/Info.txt
echo " or" >> /home/roservices/Desktop/Info.txt
echo " * Access phpMyAdmin from anywhere by browsing to http://${SERVER_IP}/phpmyadmin" >> /home/roservices/Desktop/Info.txt
echo "Access from root user is disabled, so you will need to login as 'ragnarok' with your MySQL password.\n" >> /home/roservices/Desktop/Info.txt



echo "${BLUE}Step 17/${STEPS}:${NC} Finishing up!"
sudo -u roservices sh -c "myvncserver start"
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "${YELLOW}************************ ${BLUE}All done!${NC}${YELLOW} ******************************${NC}"
echo "${GREEN} -- System Stuff${NC}"
echo "Linux User 'roservices' Password: ${RATHENAPASS}"
echo "Server IP: ${SERVER_IP}"
echo ""
echo "${GREEN} -- MySQL Stuff${NC}"
echo "MySQL user: ragnarok"
echo "MySQL password: ${USERPASS}"
echo "phpMyAdmin: http://${SERVER_IP}/phpmyadmin"
echo ""
echo "${GREEN} -- VNC Stuff${NC}"
echo "VNC Password: ch4ngem3"
echo "We recommend TightVNC Viewer: http://www.tightvnc.com/download.php"
echo "In the Remote Host box, type ${SERVER_IP}:1"
echo ""
echo "${GREEN} -- FluxCP Stuff${NC}"
echo "Control Panel: http://${SERVER_IP}/"
echo ""
echo "${BLUE}You should now use ${GREEN}sudo shutdown -r now ${BLUE}to reboot, then you can login"
echo " via VNC and click Start rAthena on the desktop.${NC}"
echo "${YELLOW}*****************************************************************${NC}"

rm /home/roservices

exit 0
